Rscript plot_file.R -i ../vibration_data/all_v5//any_cad_vibration_gather.Rdata -o ../plots/all_v5/ -v any_cad -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//any_cancer_self_report_vibration_gather.Rdata -o ../plots/all_v5/ -v any_cancer_self_report -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//any_diabetes_vibration_gather.Rdata -o ../plots/all_v5/ -v any_diabetes -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//any_family_cad_vibration_gather.Rdata -o ../plots/all_v5/ -v any_family_cad -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//any_ht_vibration_gather.Rdata -o ../plots/all_v5/ -v any_ht -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//anyone_to_help_social_vibration_gather.Rdata -o ../plots/all_v5/ -v anyone_to_help_social -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bCALCIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v bCALCIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bDIETARY_FIBER_gm_vibration_gather.Rdata -o ../plots/all_v5/ -v bDIETARY_FIBER_gm -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bFOLIC_ACID_mcg_vibration_gather.Rdata -o ../plots/all_v5/ -v bFOLIC_ACID_mcg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bMAGNESIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v bMAGNESIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bmi_vibration_gather.Rdata -o ../plots/all_v5/ -v bmi -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXBMI_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXBMI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXCALF_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXCALF -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXHT_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXHT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXLEG_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXLEG -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXSUB_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXSUB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXTHICR_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXTHICR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXTRI_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXTRI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXWAIST_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXWAIST -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BMXWT_vibration_gather.Rdata -o ../plots/all_v5/ -v BMXWT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bPHOSPHORUS_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v bPHOSPHORUS_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bPOTASSIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v bPOTASSIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//BPXPLS_vibration_gather.Rdata -o ../plots/all_v5/ -v BPXPLS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bSODIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v bSODIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//bVITAMIN_A_mcg_vibration_gather.Rdata -o ../plots/all_v5/ -v bVITAMIN_A_mcg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//CALCIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v CALCIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//CFDFINSH_vibration_gather.Rdata -o ../plots/all_v5/ -v CFDFINSH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//CFDRIGHT_vibration_gather.Rdata -o ../plots/all_v5/ -v CFDRIGHT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//community_supply_vibration_gather.Rdata -o ../plots/all_v5/ -v community_supply -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//COPPER_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v COPPER_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//current_past_smoking_vibration_gather.Rdata -o ../plots/all_v5/ -v current_past_smoking -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DBD100_vibration_gather.Rdata -o ../plots/all_v5/ -v DBD100 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DBQ095_vibration_gather.Rdata -o ../plots/all_v5/ -v DBQ095 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DMDMARTL_vibration_gather.Rdata -o ../plots/all_v5/ -v DMDMARTL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TACAR_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TACAR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TALCO_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TALCO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TATOC_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TATOC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TBCAR_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TBCAR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCAFF_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCAFF -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCALC_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCALC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCARB_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCARB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCARO_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCARO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCHOL_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCHOL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCOPP_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCOPP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TCRYP_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TCRYP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TFA_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TFA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TFDFE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TFDFE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TFF_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TFF -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TFIBE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TFIBE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TFOLA_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TFOLA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TIRON_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TIRON -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TKCAL_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TKCAL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TLYCO_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TLYCO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TLZ_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TLZ -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TM161_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TM161 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TM181_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TM181 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TM201_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TM201 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TM221_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TM221 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TMAGN_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TMAGN -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TMFAT_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TMFAT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TMOIS_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TMOIS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TNIAC_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TNIAC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP182_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP182 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP183_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP183 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP184_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP184 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP204_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP204 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP205_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP205 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP225_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP225 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TP226_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TP226 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TPFAT_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TPFAT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TPHOS_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TPHOS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TPOTA_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TPOTA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TPROT_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TPROT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TRET_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TRET -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS040_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS040 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS060_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS060 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS080_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS080 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS100_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS100 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS120_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS120 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS140_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS140 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS160_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS160 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TS180_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TS180 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TSELE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TSELE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TSFAT_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TSFAT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TSODI_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TSODI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TSUGR_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TSUGR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TTFAT_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TTFAT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TTHEO_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TTHEO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVAIU_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVAIU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVARA_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVARA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVARE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVARE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVB1_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVB1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVB12_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVB12 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVB2_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVB2 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVB6_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVB6 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVC_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TVK_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TVK -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TWATE_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TWATE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DR1TZINC_vibration_gather.Rdata -o ../plots/all_v5/ -v DR1TZINC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//drink_five_per_day_vibration_gather.Rdata -o ../plots/all_v5/ -v drink_five_per_day -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//DSDCOUNT_vibration_gather.Rdata -o ../plots/all_v5/ -v DSDCOUNT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//education_vibration_gather.Rdata -o ../plots/all_v5/ -v education -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//first_degree_support_vibration_gather.Rdata -o ../plots/all_v5/ -v first_degree_support -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//FOLIC_ACID_mcg_vibration_gather.Rdata -o ../plots/all_v5/ -v FOLIC_ACID_mcg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//foundation_treat_vibration_gather.Rdata -o ../plots/all_v5/ -v foundation_treat -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//hepa_vibration_gather.Rdata -o ../plots/all_v5/ -v hepa -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//hepb_vibration_gather.Rdata -o ../plots/all_v5/ -v hepb -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//house_age_vibration_gather.Rdata -o ../plots/all_v5/ -v house_age -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//house_type_vibration_gather.Rdata -o ../plots/all_v5/ -v house_type -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//how_many_years_in_house_vibration_gather.Rdata -o ../plots/all_v5/ -v how_many_years_in_house -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//IRON_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v IRON_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBD199_vibration_gather.Rdata -o ../plots/all_v5/ -v LBD199 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDATCSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDATCSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDBANO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDBANO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDEONO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDEONO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDHBG_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDHBG -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDHCV_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDHCV -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDHDD_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDHDD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDHDL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDHDL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDLDL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDLDL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDLYMNO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDLYMNO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDMONO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDMONO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDNENO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDNENO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDP3_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDP3 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBDPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBDPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX028_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX028 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX052_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX052 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX066_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX066 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX074_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX074 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX087_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX087 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX099_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX099 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX101_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX101 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX105_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX105 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX110_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX110 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX118_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX118 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX128_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX128 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX138_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX138 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX146_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX146 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX149_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX149 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX151_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX151 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX153_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX153 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX156_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX156 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX157_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX157 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX167_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX167 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX170_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX170 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX172_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX172 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX177_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX177 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX178_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX178 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX180_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX180 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX183_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX183 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX187_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX187 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX189_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX189 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX194_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX194 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX195_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX195 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX196_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX196 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBX206_vibration_gather.Rdata -o ../plots/all_v5/ -v LBX206 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXACR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXACR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXACY_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXACY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXALC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXALC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXALD_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXALD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXB12_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXB12 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBAP_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBAP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBAPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBAPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBCC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBCC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBCD_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBCD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBEC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBEC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBHC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBHC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXBPB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXBPB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCBC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCBC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCLC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCLC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCLZ_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCLZ -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCOT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCOT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCPSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCPSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCRP_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCRP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXCRY_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXCRY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD01_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD01 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD02_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD02 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD03_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD03 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD04_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD04 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD05_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD05 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXD07_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXD07 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXDIE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXDIE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXDTC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXDTC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXEND_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXEND -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXEOPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXEOPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXEPAH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXEPAH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXEPP_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXEPP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF01_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF01 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF02_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF02 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF03_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF03 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF04_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF04 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF05_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF05 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF06_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF06 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF07_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF07 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF08_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF08 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF09_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF09 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXF10_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXF10 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXFB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXFB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXFER_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXFER -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXFOL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXFOL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXGH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXGH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXGHC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXGHC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXGLU_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXGLU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXGLY_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXGLY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXGTC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXGTC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHBC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHBC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHBS_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHBS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHCB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHCB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHCY_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHCY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHGB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHGB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHP1_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHP1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHPE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHPE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXHXC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXHXC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXIHG_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXIHG -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXIN_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXIN -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXIRN_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXIRN -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXLCC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXLCC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXLUT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXLUT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXLUZ_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXLUZ -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXLYC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXLYC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXLYPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXLYPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXM1_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXM1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMCHSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMCHSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMCVSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMCVSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMIR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMIR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMMA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMMA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMOPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMOPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMPAH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMPAH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMPSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMPSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXMS1_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXMS1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXNEPCT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXNEPCT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXODT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXODT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXOXY_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXOXY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXP1_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXP1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXP2_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXP2 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPCB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPCB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPDE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPDE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPDT_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPDT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFDE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFDE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFDO_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFDO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFHP_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFHP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFHS_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFHS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFNA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFNA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFOA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFOA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFOS_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFOS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFSA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFSA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPFUA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPFUA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPHE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPHE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPHF_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPHF -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPLTSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPLTSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXPT21_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXPT21 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXRBCSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXRBCSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXRBF_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXRBF -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXRDW_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXRDW -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXRPL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXRPL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXRST_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXRST -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSAL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSAL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSAPSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSAPSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSASSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSASSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSATSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSATSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSBU_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSBU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSC3SI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSC3SI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSCA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSCA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSCH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSCH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSCLSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSCLSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSCR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSCR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSCRINV_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSCRINV -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSEL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSEL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSGB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSGB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSGL_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSGL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSGTSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSGTSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSIR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSIR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSKSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSKSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSLDSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSLDSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSNASI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSNASI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSOSSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSOSSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSPH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSPH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSTB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSTB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSTP_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSTP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSTR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSTR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXSUA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXSUA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXT4_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXT4 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTC2_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTC2 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTCD_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTCD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTHG_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTHG -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTIB_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTIB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTNA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTNA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTR_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXTSH_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXTSH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXVB6_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXVB6 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXVIA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXVIA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXVIC_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXVIC -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXVID_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXVID -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXVIE_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXVIE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXWBCSI_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXWBCSI -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//LBXZEA_vibration_gather.Rdata -o ../plots/all_v5/ -v LBXZEA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//lite_salt_vibration_gather.Rdata -o ../plots/all_v5/ -v lite_salt -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//MAGNESIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v MAGNESIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//male_vibration_gather.Rdata -o ../plots/all_v5/ -v male -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//MDIS_vibration_gather.Rdata -o ../plots/all_v5/ -v MDIS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//MSYS_vibration_gather.Rdata -o ../plots/all_v5/ -v MSYS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//no_salt_vibration_gather.Rdata -o ../plots/all_v5/ -v no_salt -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//number_close_friends_vibration_gather.Rdata -o ../plots/all_v5/ -v number_close_friends -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//occupation_vibration_gather.Rdata -o ../plots/all_v5/ -v occupation -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//ordinary_salt_vibration_gather.Rdata -o ../plots/all_v5/ -v ordinary_salt -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//pest_control_home_last_month_vibration_gather.Rdata -o ../plots/all_v5/ -v pest_control_home_last_month -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//pest_control_yard_last_month_vibration_gather.Rdata -o ../plots/all_v5/ -v pest_control_yard_last_month -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//PHOSPHORUS_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v PHOSPHORUS_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//physical_activity_vibration_gather.Rdata -o ../plots/all_v5/ -v physical_activity -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//pneu_vibration_gather.Rdata -o ../plots/all_v5/ -v pneu -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//POTASSIUM_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v POTASSIUM_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//private_water_source_vibration_gather.Rdata -o ../plots/all_v5/ -v private_water_source -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//quantity_drink_per_day_vibration_gather.Rdata -o ../plots/all_v5/ -v quantity_drink_per_day -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//RIBOFLAVIN_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v RIBOFLAVIN_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//RIDAGEYR_vibration_gather.Rdata -o ../plots/all_v5/ -v RIDAGEYR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//RIDRETH1_vibration_gather.Rdata -o ../plots/all_v5/ -v RIDRETH1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//rooms_treated_vibration_gather.Rdata -o ../plots/all_v5/ -v rooms_treated -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//salt_substitute_vibration_gather.Rdata -o ../plots/all_v5/ -v salt_substitute -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SELENIUM_mcg_vibration_gather.Rdata -o ../plots/all_v5/ -v SELENIUM_mcg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SES_LEVEL_vibration_gather.Rdata -o ../plots/all_v5/ -v SES_LEVEL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SMD410_vibration_gather.Rdata -o ../plots/all_v5/ -v SMD410 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SMD415_vibration_gather.Rdata -o ../plots/all_v5/ -v SMD415 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SMD415A_vibration_gather.Rdata -o ../plots/all_v5/ -v SMD415A -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//SMD430_vibration_gather.Rdata -o ../plots/all_v5/ -v SMD430 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//supplement_count_vibration_gather.Rdata -o ../plots/all_v5/ -v supplement_count -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//TBQ020_vibration_gather.Rdata -o ../plots/all_v5/ -v TBQ020 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//TBQ040_vibration_gather.Rdata -o ../plots/all_v5/ -v TBQ040 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//TBQ060_vibration_gather.Rdata -o ../plots/all_v5/ -v TBQ060 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//THIAMIN_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v THIAMIN_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//total_days_drink_year_vibration_gather.Rdata -o ../plots/all_v5/ -v total_days_drink_year -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//treatment_in_home_non_pro_vibration_gather.Rdata -o ../plots/all_v5/ -v treatment_in_home_non_pro -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//treatment_in_yard_non_pro_vibration_gather.Rdata -o ../plots/all_v5/ -v treatment_in_yard_non_pro -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXDAZ_vibration_gather.Rdata -o ../plots/all_v5/ -v URXDAZ -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXDMA_vibration_gather.Rdata -o ../plots/all_v5/ -v URXDMA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXDPY_vibration_gather.Rdata -o ../plots/all_v5/ -v URXDPY -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXEQU_vibration_gather.Rdata -o ../plots/all_v5/ -v URXEQU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXETD_vibration_gather.Rdata -o ../plots/all_v5/ -v URXETD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXETL_vibration_gather.Rdata -o ../plots/all_v5/ -v URXETL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXGNS_vibration_gather.Rdata -o ../plots/all_v5/ -v URXGNS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMBP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMBP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMC1_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMC1 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMCP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMCP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMEP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMEP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMET_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMET -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMHH_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMHH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMHP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMHP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMIB_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMIB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMNM_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMNM -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMNP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMNP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMOH_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMOH -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMOP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMOP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXMZP_vibration_gather.Rdata -o ../plots/all_v5/ -v URXMZP -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXNT_vibration_gather.Rdata -o ../plots/all_v5/ -v URXNT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP01_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP01 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP02_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP02 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP03_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP03 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP04_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP04 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP05_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP05 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP06_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP06 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP07_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP07 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP08_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP08 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP10_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP10 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP11_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP11 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP12_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP12 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP13_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP13 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP14_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP14 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP15_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP15 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP16_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP16 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP17_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP17 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP19_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP19 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP20_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP20 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP21_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP21 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP22_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP22 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXP24_vibration_gather.Rdata -o ../plots/all_v5/ -v URXP24 -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUBA_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUBA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUBE_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUBE -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUCD_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUCD -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUCO_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUCO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUCR_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUCR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUCS_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUCS -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUIO_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUIO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUMA_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUMA -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUMO_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUMO -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUPB_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUPB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUPT_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUPT -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUSB_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUSB -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUTL_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUTL -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUTU_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUTU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//URXUUR_vibration_gather.Rdata -o ../plots/all_v5/ -v URXUUR -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//use_water_treatment_vibration_gather.Rdata -o ../plots/all_v5/ -v use_water_treatment -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//VITAMIN_A_IU_vibration_gather.Rdata -o ../plots/all_v5/ -v VITAMIN_A_IU -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//VITAMIN_B_12_mcg_vibration_gather.Rdata -o ../plots/all_v5/ -v VITAMIN_B_12_mcg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//VITAMIN_B_6_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v VITAMIN_B_6_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//VITAMIN_C_mg_vibration_gather.Rdata -o ../plots/all_v5/ -v VITAMIN_C_mg -d ../dictionary/dictionary.Rdata
Rscript plot_file.R -i ../vibration_data/all_v5//well_water_vibration_gather.Rdata -o ../plots/all_v5/ -v well_water -d ../dictionary/dictionary.Rdata
