Rscript plot_file.R -i ../../vibration_data/all_v5//any_cad_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v any_cad -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//any_cancer_self_report_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v any_cancer_self_report -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//any_diabetes_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v any_diabetes -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//any_family_cad_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v any_family_cad -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//any_ht_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v any_ht -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//anyone_to_help_social_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v anyone_to_help_social -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bCALCIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bCALCIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bDIETARY_FIBER_gm_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bDIETARY_FIBER_gm -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bFOLIC_ACID_mcg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bFOLIC_ACID_mcg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bMAGNESIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bMAGNESIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bmi_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bmi -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXBMI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXBMI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXCALF_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXCALF -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXHT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXHT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXLEG_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXLEG -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXSUB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXSUB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXTHICR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXTHICR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXTRI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXTRI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXWAIST_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXWAIST -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BMXWT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BMXWT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bPHOSPHORUS_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bPHOSPHORUS_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bPOTASSIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bPOTASSIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//BPXPLS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v BPXPLS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bSODIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bSODIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//bVITAMIN_A_mcg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v bVITAMIN_A_mcg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//CALCIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v CALCIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//CFDFINSH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v CFDFINSH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//CFDRIGHT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v CFDRIGHT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//community_supply_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v community_supply -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//COPPER_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v COPPER_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//current_past_smoking_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v current_past_smoking -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DBD100_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DBD100 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DBQ095_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DBQ095 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DMDMARTL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DMDMARTL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TACAR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TACAR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TALCO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TALCO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TATOC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TATOC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TBCAR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TBCAR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCAFF_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCAFF -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCALC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCALC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCARB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCARB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCARO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCARO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCHOL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCHOL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCOPP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCOPP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TCRYP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TCRYP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TFA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TFA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TFDFE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TFDFE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TFF_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TFF -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TFIBE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TFIBE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TFOLA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TFOLA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TIRON_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TIRON -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TKCAL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TKCAL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TLYCO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TLYCO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TLZ_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TLZ -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TM161_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TM161 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TM181_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TM181 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TM201_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TM201 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TM221_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TM221 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TMAGN_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TMAGN -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TMFAT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TMFAT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TMOIS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TMOIS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TNIAC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TNIAC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP182_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP182 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP183_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP183 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP184_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP184 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP204_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP204 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP205_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP205 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP225_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP225 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TP226_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TP226 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TPFAT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TPFAT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TPHOS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TPHOS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TPOTA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TPOTA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TPROT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TPROT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TRET_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TRET -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS040_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS040 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS060_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS060 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS080_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS080 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS100_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS100 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS120_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS120 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS140_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS140 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS160_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS160 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TS180_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TS180 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TSELE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TSELE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TSFAT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TSFAT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TSODI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TSODI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TSUGR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TSUGR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TTFAT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TTFAT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TTHEO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TTHEO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVAIU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVAIU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVARA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVARA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVARE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVARE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVB1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVB1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVB12_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVB12 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVB2_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVB2 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVB6_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVB6 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TVK_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TVK -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TWATE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TWATE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DR1TZINC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DR1TZINC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//drink_five_per_day_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v drink_five_per_day -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//DSDCOUNT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v DSDCOUNT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//education_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v education -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//first_degree_support_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v first_degree_support -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//FOLIC_ACID_mcg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v FOLIC_ACID_mcg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//foundation_treat_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v foundation_treat -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//hepa_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v hepa -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//hepb_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v hepb -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//house_age_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v house_age -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//house_type_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v house_type -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//how_many_years_in_house_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v how_many_years_in_house -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//IRON_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v IRON_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBD199_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBD199 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDATCSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDATCSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDBANO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDBANO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDEONO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDEONO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDHBG_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDHBG -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDHCV_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDHCV -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDHDD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDHDD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDHDL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDHDL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDLDL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDLDL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDLYMNO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDLYMNO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDMONO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDMONO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDNENO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDNENO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDP3_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDP3 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBDPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBDPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX028_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX028 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX052_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX052 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX066_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX066 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX074_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX074 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX087_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX087 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX099_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX099 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX101_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX101 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX105_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX105 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX110_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX110 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX118_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX118 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX128_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX128 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX138_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX138 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX146_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX146 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX149_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX149 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX151_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX151 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX153_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX153 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX156_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX156 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX157_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX157 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX167_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX167 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX170_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX170 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX172_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX172 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX177_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX177 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX178_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX178 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX180_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX180 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX183_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX183 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX187_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX187 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX189_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX189 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX194_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX194 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX195_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX195 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX196_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX196 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBX206_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBX206 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXACR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXACR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXACY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXACY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXALC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXALC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXALD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXALD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXB12_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXB12 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBAP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBAP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBAPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBAPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBCC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBCC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBCD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBCD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBEC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBEC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBHC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBHC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXBPB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXBPB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCBC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCBC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCLC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCLC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCLZ_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCLZ -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCOT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCOT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCPSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCPSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCRP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCRP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXCRY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXCRY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD01_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD01 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD02_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD02 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD03_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD03 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD04_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD04 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD05_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD05 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXD07_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXD07 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXDIE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXDIE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXDTC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXDTC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXEND_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXEND -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXEOPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXEOPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXEPAH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXEPAH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXEPP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXEPP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF01_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF01 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF02_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF02 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF03_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF03 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF04_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF04 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF05_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF05 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF06_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF06 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF07_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF07 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF08_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF08 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF09_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF09 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXF10_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXF10 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXFB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXFB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXFER_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXFER -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXFOL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXFOL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXGH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXGH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXGHC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXGHC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXGLU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXGLU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXGLY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXGLY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXGTC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXGTC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHBC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHBC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHBS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHBS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHCB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHCB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHCY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHCY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHGB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHGB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHP1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHP1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHPE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHPE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXHXC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXHXC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXIHG_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXIHG -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXIN_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXIN -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXIRN_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXIRN -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXLCC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXLCC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXLUT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXLUT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXLUZ_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXLUZ -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXLYC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXLYC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXLYPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXLYPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXM1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXM1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMCHSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMCHSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMCVSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMCVSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMIR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMIR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMMA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMMA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMOPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMOPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMPAH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMPAH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMPSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMPSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXMS1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXMS1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXNEPCT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXNEPCT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXODT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXODT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXOXY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXOXY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXP1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXP1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXP2_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXP2 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPCB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPCB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPDE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPDE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPDT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPDT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFDE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFDE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFDO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFDO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFHP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFHP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFHS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFHS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFNA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFNA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFOA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFOA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFOS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFOS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFSA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFSA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPFUA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPFUA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPHE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPHE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPHF_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPHF -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPLTSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPLTSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXPT21_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXPT21 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXRBCSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXRBCSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXRBF_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXRBF -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXRDW_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXRDW -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXRPL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXRPL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXRST_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXRST -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSAL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSAL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSAPSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSAPSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSASSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSASSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSATSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSATSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSBU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSBU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSC3SI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSC3SI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSCA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSCA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSCH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSCH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSCLSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSCLSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSCR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSCR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSCRINV_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSCRINV -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSEL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSEL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSGB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSGB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSGL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSGL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSGTSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSGTSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSIR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSIR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSKSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSKSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSLDSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSLDSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSNASI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSNASI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSOSSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSOSSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSPH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSPH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSTB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSTB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSTP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSTP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSTR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSTR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXSUA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXSUA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXT4_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXT4 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTC2_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTC2 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTCD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTCD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTHG_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTHG -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTIB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTIB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTNA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTNA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXTSH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXTSH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXVB6_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXVB6 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXVIA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXVIA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXVIC_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXVIC -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXVID_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXVID -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXVIE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXVIE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXWBCSI_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXWBCSI -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//LBXZEA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v LBXZEA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//lite_salt_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v lite_salt -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//MAGNESIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v MAGNESIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//male_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v male -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//MDIS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v MDIS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//MSYS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v MSYS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//no_salt_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v no_salt -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//number_close_friends_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v number_close_friends -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//occupation_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v occupation -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//ordinary_salt_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v ordinary_salt -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//pest_control_home_last_month_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v pest_control_home_last_month -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//pest_control_yard_last_month_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v pest_control_yard_last_month -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//PHOSPHORUS_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v PHOSPHORUS_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//physical_activity_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v physical_activity -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//pneu_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v pneu -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//POTASSIUM_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v POTASSIUM_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//private_water_source_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v private_water_source -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//quantity_drink_per_day_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v quantity_drink_per_day -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//RIBOFLAVIN_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v RIBOFLAVIN_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//RIDAGEYR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v RIDAGEYR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//RIDRETH1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v RIDRETH1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//rooms_treated_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v rooms_treated -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//salt_substitute_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v salt_substitute -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SELENIUM_mcg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SELENIUM_mcg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SES_LEVEL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SES_LEVEL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SMD410_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SMD410 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SMD415_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SMD415 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SMD415A_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SMD415A -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//SMD430_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v SMD430 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//supplement_count_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v supplement_count -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//TBQ020_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v TBQ020 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//TBQ040_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v TBQ040 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//TBQ060_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v TBQ060 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//THIAMIN_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v THIAMIN_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//total_days_drink_year_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v total_days_drink_year -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//treatment_in_home_non_pro_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v treatment_in_home_non_pro -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//treatment_in_yard_non_pro_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v treatment_in_yard_non_pro -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXDAZ_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXDAZ -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXDMA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXDMA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXDPY_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXDPY -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXEQU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXEQU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXETD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXETD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXETL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXETL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXGNS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXGNS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMBP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMBP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMC1_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMC1 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMCP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMCP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMEP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMEP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMET_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMET -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMHH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMHH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMHP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMHP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMIB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMIB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMNM_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMNM -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMNP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMNP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMOH_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMOH -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMOP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMOP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXMZP_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXMZP -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXNT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXNT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP01_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP01 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP02_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP02 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP03_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP03 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP04_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP04 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP05_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP05 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP06_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP06 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP07_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP07 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP08_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP08 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP10_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP10 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP11_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP11 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP12_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP12 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP13_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP13 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP14_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP14 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP15_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP15 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP16_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP16 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP17_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP17 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP19_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP19 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP20_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP20 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP21_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP21 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP22_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP22 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXP24_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXP24 -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUBA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUBA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUBE_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUBE -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUCD_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUCD -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUCO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUCO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUCR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUCR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUCS_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUCS -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUIO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUIO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUMA_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUMA -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUMO_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUMO -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUPB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUPB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUPT_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUPT -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUSB_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUSB -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUTL_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUTL -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUTU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUTU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//URXUUR_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v URXUUR -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//use_water_treatment_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v use_water_treatment -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//VITAMIN_A_IU_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v VITAMIN_A_IU -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//VITAMIN_B_12_mcg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v VITAMIN_B_12_mcg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//VITAMIN_B_6_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v VITAMIN_B_6_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//VITAMIN_C_mg_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v VITAMIN_C_mg -d ../../data/dictionary/dictionary.Rdata
Rscript plot_file.R -i ../../vibration_data/all_v5//well_water_vibration_gather.Rdata -o ../../plots/all_v4_small/ -v well_water -d ../../data/dictionary/dictionary.Rdata
