bsub -q short -W 11:59 -J LBXVID_0_s0 -o ../../params/LBXVID_0_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_0_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_1_s0 -o ../../params/LBXVID_1_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_1_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_10_s0 -o ../../params/LBXVID_10_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_10_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_11_s0 -o ../../params/LBXVID_11_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_11_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_12_s0 -o ../../params/LBXVID_12_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_12_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_13_s0 -o ../../params/LBXVID_13_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_13_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_14_s0 -o ../../params/LBXVID_14_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_14_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_15_s0 -o ../../params/LBXVID_15_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_15_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_16_s0 -o ../../params/LBXVID_16_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_16_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_17_s0 -o ../../params/LBXVID_17_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_17_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_18_s0 -o ../../params/LBXVID_18_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_18_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_19_s0 -o ../../params/LBXVID_19_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_19_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_2_s0 -o ../../params/LBXVID_2_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_2_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_3_s0 -o ../../params/LBXVID_3_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_3_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_4_s0 -o ../../params/LBXVID_4_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_4_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_5_s0 -o ../../params/LBXVID_5_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_5_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_6_s0 -o ../../params/LBXVID_6_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_6_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_7_s0 -o ../../params/LBXVID_7_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_7_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_8_s0 -o ../../params/LBXVID_8_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_8_s0_param.Rdata
bsub -q short -W 11:59 -J LBXVID_9_s0 -o ../../params/LBXVID_9_s0.out Rscript vibrationAnalysisK.R -p ../../params/LBXVID_9_s0_param.Rdata
